### ISSUE TITLE
ImportError: cannot import name _calculateCrcString

### ISSUE THREAD

**Issue by smirrom** [sergray/energy-meter-mercury206#2]
Установил так, как написано в Readme:
```
$ pip install git+https://github.com/sergray/energy-meter-mercury206.git
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. pip 21.0 will drop support for Python 2.7 in January 2021. More details about Python 2 support in pip can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
Collecting git+https://github.com/sergray/energy-meter-mercury206.git
  Cloning https://github.com/sergray/energy-meter-mercury206.git to /tmp/pip-req-build-GXOSeQ
Requirement already satisfied (use --upgrade to upgrade): energy-meter-mercury206==0.0.3 from git+https://github.com/sergray/energy-meter-mercury206.git in ./mercury206.env/lib/python2.7/site-packages
Requirement already satisfied: minimalmodbus in ./mercury206.env/lib/python2.7/site-packages (from energy-meter-mercury206==0.0.3) (1.0.2)
Requirement already satisfied: pyserial in ./mercury206.env/lib/python2.7/site-packages (from energy-meter-mercury206==0.0.3) (3.4)
Building wheels for collected packages: energy-meter-mercury206
  Building wheel for energy-meter-mercury206 (setup.py) ... done
  Created wheel for energy-meter-mercury206: filename=energy_meter_mercury206-0.0.3-py2.py3-none-any.whl size=9193 sha256=7dc7874c66a192a49e15d90f2299df4ed99bd12f315937caa0c3d2ab07bf78f6
  Stored in directory: /tmp/pip-ephem-wheel-cache-gpTrRy/wheels/5e/75/4d/7b765ab3edce008866e88353569a08ad27b31dc030b60205e1
Successfully built energy-meter-mercury206
(mercury206.env)
```

При запуске получаю ошибку:

```
$ mercury206_config
Traceback (most recent call last):
  File "/home/Smirrom/mercury206.env/bin/mercury206_config", line 5, in <module>
    from mercury206.scripts import sample_config
  File "/home/Smirrom/mercury206.env/lib/python2.7/site-packages/mercury206/scripts.py", line 9, in <module>
    from communications import open_serial
  File "/home/Smirrom/mercury206.env/lib/python2.7/site-packages/mercury206/communications.py", line 10, in <module>
    from protocol import pack_msg, unpack_msg
  File "/home/Smirrom/mercury206.env/lib/python2.7/site-packages/mercury206/protocol.py", line 5, in <module>
    from minimalmodbus import _calculateCrcString as modbus_crc
ImportError: cannot import name _calculateCrcString
```

**Comment by sergray** [comment]
@smirrom спасибо за отчёт с ошибкой. Исправил её в новой версии.
